require("globals")
require("settings")
require("keymappings")
require("plugins")
require("colorscheme")

require("treesitter-lua")
require("autopairs-lua")
require("rainbow_parentheses-lua")
require("gitsigns-lua")
require("comment-lua")
require("devicons-lua")
require("lir-lua")
require("vimtex-lua")
require("indent_blankline-lua")
require("telescope-lua")
require("lspinstall-lua")
require("lspsaga-lua")
require("lsp_signature-lua")
require("compe-lua")

require("lsp")
