abbr --add ga "git add"
abbr --add gst "git status"
abbr --add gl "git pull"
abbr --add gp "git push"
abbr --add gpu "git push -u"
abbr --add gcl "git clone"
abbr --add gc "git commit -v"
abbr --add gco "git checkout"
abbr --add gra "git remote add"
alias glol "git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
abbr --add gwt "git worktree"
abbr --add gwta "git worktree add"
abbr --add gwtrm "git worktree remove"
abbr --add gwtl "git worktree list"
