version: 2
root-markers:
  - .git/
tools:
  python-flake8: &python-flake8
    lint-command: 'flake8 --stdin-display-name ${INPUT} -'
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %m'

  python-black: &python-black
    format-command: 'black --quiet -'
    format-stdin: true

  python-isort: &python-isort
    format-command: 'isort --stdout -'
    format-stdin: true

  lua-luaformat: &lua-luaformat
    # format-command: 'lua-format -i --no-keep-simple-function-one-line --no-break-after-operator --column-limit=150 --break-after-table-lb'
    format-command: 'lua-format -c ~/.config/lua-format/config'
    format-stdin: true

languages:
  python:
    - <<: *python-black
    - <<: *python-flake8
    - <<: *python-isort
  lua:
    - <<: *lua-luaformat
