# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.config/zsh/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

autoload -Uz compinit && compinit

# Better Search History
autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search

bindkey "^[[A" up-line-or-beginning-search
bindkey "^[[B" down-line-or-beginning-search

export EDITOR="nvim"

source "$ZDOTDIR/zsh-functions.zsh"

zsh_add_file "zsh-aliases.zsh"
zsh_add_file "zsh-git-aliases.zsh"
zsh_add_file "zsh-options.zsh"
zsh_add_file "pyenv.zsh"

antidote_home="${XDG_DATA_HOME:-${HOME}/.local/share}/zsh/antidote/"

# If antidote (plugin manager) is not installed, install it
if [ ! -d "$antidote_home" ]; then
	mkdir -p "$antidote_home"
	git clone --depth=1 https://github.com/mattmc3/antidote.git ${antidote_home}
fi

# If plugins file is newer than static load file, regenerate static load file
zsh_plugins=${ZDOTDIR}/zsh_plugins
if [[ ! ${zsh_plugins}.zsh -nt {zsh_plugins}.txt ]]; then
	source "${antidote_home}/antidote.zsh"
	antidote bundle < ${zsh_plugins}.txt > ${zsh_plugins}.zsh
fi

# Load plugins
source ${zsh_plugins}.zsh
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=#7E959E'

# To customize prompt, run `p10k configure` or edit ~/.config/zsh/.p10k.zsh.
[[ ! -f ~/.config/zsh/p10k.zsh ]] || source ~/.config/zsh/p10k.zsh
