autoload -Uz compinit
export LS_COLORS=$(vivid generate everforest)
zstyle ':completion:*' menu select
zstyle ':completion:*' list-colors "${LS_COLORS}"
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zmodload zsh/complist

_comp_options+=(globdots)

# Better search history
autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey "^[OA" up-line-or-beginning-search
bindkey "^[OB" down-line-or-beginning-search
 
# Edit line in vim with ctrl-e
autoload edit-command-line; zle -N edit-command-line
bindkey '^e' edit-command-line

# Fix BS delete and home
bindkey "^?" backward-delete-char
bindkey "^[[H" beginning-of-line
bindkey "^[[F" end-of-line
bindkey "^[[3~" delete-char
bindkey "^[[Z" menu-complete

source "$ZDOTDIR/zsh-functions"

# Source config files
zsh_add_file "zsh-aliases"
zsh_add_file "zsh-git-aliases"
zsh_add_file "zsh-options"
zsh_add_file "zsh-prompt"

# Plugins
zsh_add_plugin "zsh-users/zsh-autosuggestions"
zsh_add_plugin "zsh-users/zsh-syntax-highlighting"

# Autosuggest Settings
ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=20
ZSH_AUTOSUGGEST_USE_ASYNC=1
bindkey '^j' autosuggest-accept
bindkey '^k' autosuggest-execute

# FZF
source ~/.config/fzf/completion.zsh
source ~/.config/fzf/key-bindings.zsh
export FZF_DEFAULT_OPTS='--height 40% --border'
# fe - opens file in $EDITOR instead of returning it to command line
fe() {
  local files
  IFS=$'\n' files=($(fzf-tmux --query="$1" --multi --select-1 --exit-0))
  [[ -n "$files" ]] && ${EDITOR:-vim} "${files[@]}"
}

# fd - cd to selected directory
fd() {
  local dir
  dir=$(find ${1:-.} -path '*/\.*' -prune \
                  -o -type d -print 2> /dev/null | fzf +m) &&
  cd "$dir"
}

# fbr - checkout git branch
fbr() {
  local branches branch
  branches=$(git branch --all | grep -v HEAD) &&
  branch=$(echo "$branches" |
           fzf-tmux -d $(( 2 + $(wc -l <<< "$branches") )) +m) &&
  git checkout $(echo "$branch" | sed "s/.* //" | sed "s#remotes/[^/]*/##")
}

# Pyenv
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PATH:$PYENV_ROOT/bin"
export WORKON_HOME=~/.ve
export PROJECT_HOME=~/projects
eval "$(pyenv init - --no-rehash zsh)"
pyenv virtualenvwrapper_lazy

# NPM
export PATH="$HOME/.npm-global/bin:$PATH"

# Luarocks
export PATH="$HOME/.luarocks/bin:$PATH"
