autoload -Uz compinit
zstyle ':completion:*' menu select
zmodload zsh/complist

_comp_options+=(globdots)

# Better search history
autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey "^[[A" up-line-or-beginning-search
bindkey "^[[B" down-line-or-beginning-search

# Fix BS delete and home
bindkey "^?" backward-delete-char
bindkey "^[[7~" beginning-of-line
bindkey "^[[8~" end-of-line
bindkey "^[[3~" delete-char
bindkey "^[[Z" menu-complete

source "$ZDOTDIR/zsh-functions"

# Source config files
zsh_add_file "zsh-aliases"
unsetopt beep nomatch
zsh_add_file "zsh-options"

# Plugins
zsh_add_plugins "zsh-users/zsh-autosuggestions"
zsh_add_plugins "zsh-users/zsh-syntax-highlighting"

# Autosuggest Settings
ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=20
ZSH_AUTOSUGGEST_USE_ASYNC=1
bindkey '^j' autosuggest-accept
bindkey '^k' autosuggest-execute

# FZF
source ~/.config/fzf/completion.zsh
source ~/.config/fzf/key-bindings.zsh
export FZF_DEFAULT_OPTS='--height 40% --border'
# fe - opens file in $EDITOR instead of returning it to command line
fe() {
  local files
  IFS=$'\n' files=($(fzf-tmux --query="$1" --multi --select-1 --exit-0))
  [[ -n "$files" ]] && ${EDITOR:-vim} "${files[@]}"
}

# fd - cd to selected directory
fd() {
  local dir
  dir=$(find ${1:-.} -path '*/\.*' -prune \
                  -o -type d -print 2> /dev/null | fzf +m) &&
  cd "$dir"
}

# fbr - checkout git branch
fbr() {
  local branches branch
  branches=$(git branch --all | grep -v HEAD) &&
  branch=$(echo "$branches" |
           fzf-tmux -d $(( 2 + $(wc -l <<< "$branches") )) +m) &&
  git checkout $(echo "$branch" | sed "s/.* //" | sed "s#remotes/[^/]*/##")
}

# Pyenv
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PATH:$PYENV_ROOT/bin"
export WORKON_HOME=~/.ve
export PROJECT_HOME=~/projects
eval "$(pyenv init -)"
pyenv virtualenvwrapper_lazy

# NPM
export PATH="$PATH:$HOME/.npm-global/bin"
