fish_color_autosuggestion 7A8478
fish_color_cancel --reverse
fish_color_command green
fish_color_comment 7A8478 '--italics'
fish_color_cwd 7FBBB3
fish_color_cwd_root bf616a
fish_color_end E69875
fish_color_error E67E80
fish_color_escape DBBC7F
fish_color_gray 7A8478
fish_color_hg_added A7C080
fish_color_hg_clean A7C080
fish_color_hg_copied D699B6
fish_color_hg_deleted E67E80
fish_color_hg_dirty E67E80
fish_color_hg_modified DBBC7F
fish_color_hg_renamed D699B6
fish_color_hg_unmerged E67E80
fish_color_hg_untracked DBBC7F
fish_color_history_current D3C6AA '--bold'
fish_color_host a3be8c
fish_color_host_remote
fish_color_keyword
fish_color_match --background=brblue
fish_color_normal D3C6AA
fish_color_operator 81a1c1
fish_color_option
fish_color_param D3C6AA
fish_color_quote A7C080
fish_color_redirection D699B6 '--bold'
fish_color_search_match '--bold'  '--background=434c5e'
fish_color_selection 7A84782  '--bold'  '--background=434c5e'
fish_color_user A7C080
fish_color_valid_path --underline
fish_pager_color_background
fish_pager_color_completion D3C6AA
fish_pager_color_description 'ebcb8b'  '--italics'
fish_pager_color_prefix 'normal'  '--bold'  '--underline'
fish_pager_color_progress '3b4252'  '--background=d08770'
fish_pager_color_secondary_background
fish_pager_color_secondary_completion
fish_pager_color_secondary_description
fish_pager_color_secondary_prefix
fish_pager_color_selected_background --background=434c5e
fish_pager_color_selected_completion
fish_pager_color_selected_description
fish_pager_color_selected_prefix
